# Generated by Django 5.1 on 2024-08-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('diagnostics', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Records',
            fields=[
                ('record_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('diagnostics', models.CharField(max_length=100)),
                ('observations', models.TextField()),
                ('treatments', models.TextField()),
                ('misc', models.TextField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
