# Generated by Django 5.1 on 2024-08-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
        ),
    ]
